/*
 * This file is generated by jOOQ.
 */
package jooq_generated.tables;


import java.util.Arrays;
import java.util.List;

import jooq_generated.Keys;
import jooq_generated.Public;
import jooq_generated.tables.records.QuestionsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * The table <code>public.questions</code>.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Questions extends TableImpl<QuestionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.questions</code>
     */
    public static final Questions QUESTIONS = new Questions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuestionsRecord> getRecordType() {
        return QuestionsRecord.class;
    }

    /**
     * The column <code>public.questions.id</code>.
     */
    public final TableField<QuestionsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.questions.diagnostic_id</code>.
     */
    public final TableField<QuestionsRecord, Long> DIAGNOSTIC_ID = createField(DSL.name("diagnostic_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.questions.text</code>.
     */
    public final TableField<QuestionsRecord, String> TEXT = createField(DSL.name("text"), SQLDataType.VARCHAR.nullable(false), this, "");

    private Questions(Name alias, Table<QuestionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Questions(Name alias, Table<QuestionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.questions</code> table reference
     */
    public Questions(String alias) {
        this(DSL.name(alias), QUESTIONS);
    }

    /**
     * Create an aliased <code>public.questions</code> table reference
     */
    public Questions(Name alias) {
        this(alias, QUESTIONS);
    }

    /**
     * Create a <code>public.questions</code> table reference
     */
    public Questions() {
        this(DSL.name("questions"), null);
    }

    public <O extends Record> Questions(Table<O> child, ForeignKey<O, QuestionsRecord> key) {
        super(child, key, QUESTIONS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<QuestionsRecord, Long> getIdentity() {
        return (Identity<QuestionsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<QuestionsRecord> getPrimaryKey() {
        return Keys.PK_QUESTIONS;
    }

    @Override
    public List<UniqueKey<QuestionsRecord>> getKeys() {
        return Arrays.<UniqueKey<QuestionsRecord>>asList(Keys.PK_QUESTIONS);
    }

    @Override
    public List<ForeignKey<QuestionsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<QuestionsRecord, ?>>asList(Keys.QUESTIONS__QUESTIONS_DIAGNOSTIC_ID_FKEY);
    }

    private transient Diagnostic _diagnostic;

    public Diagnostic diagnostic() {
        if (_diagnostic == null)
            _diagnostic = new Diagnostic(this, Keys.QUESTIONS__QUESTIONS_DIAGNOSTIC_ID_FKEY);

        return _diagnostic;
    }

    @Override
    public Questions as(String alias) {
        return new Questions(DSL.name(alias), this);
    }

    @Override
    public Questions as(Name alias) {
        return new Questions(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Questions rename(String name) {
        return new Questions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Questions rename(Name name) {
        return new Questions(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
