/*
 * This file is generated by jOOQ.
 */
package jooq_generated.tables.pojos;


import java.io.Serializable;


/**
 * The table <code>public.clients_summary</code>.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientsSummary implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long    clientId;
    private Integer energyLevel;

    public ClientsSummary() {}

    public ClientsSummary(ClientsSummary value) {
        this.clientId = value.clientId;
        this.energyLevel = value.energyLevel;
    }

    public ClientsSummary(
        Long    clientId,
        Integer energyLevel
    ) {
        this.clientId = clientId;
        this.energyLevel = energyLevel;
    }

    /**
     * Getter for <code>public.clients_summary.client_id</code>.
     */
    public Long getClientId() {
        return this.clientId;
    }

    /**
     * Setter for <code>public.clients_summary.client_id</code>.
     */
    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    /**
     * Getter for <code>public.clients_summary.energy_level</code>.
     */
    public Integer getEnergyLevel() {
        return this.energyLevel;
    }

    /**
     * Setter for <code>public.clients_summary.energy_level</code>.
     */
    public void setEnergyLevel(Integer energyLevel) {
        this.energyLevel = energyLevel;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ClientsSummary (");

        sb.append(clientId);
        sb.append(", ").append(energyLevel);

        sb.append(")");
        return sb.toString();
    }
}
