/*
 * This file is generated by jOOQ.
 */
package jooq_generated.tables.pojos;


import java.io.Serializable;


/**
 * The table <code>public.clients</code>.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Clients implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long    id;
    private String  name;
    private String  lastname;
    private String  email;
    private String  password;
    private String  role;
    private Boolean deleted;

    public Clients() {}

    public Clients(Clients value) {
        this.id = value.id;
        this.name = value.name;
        this.lastname = value.lastname;
        this.email = value.email;
        this.password = value.password;
        this.role = value.role;
        this.deleted = value.deleted;
    }

    public Clients(
        Long    id,
        String  name,
        String  lastname,
        String  email,
        String  password,
        String  role,
        Boolean deleted
    ) {
        this.id = id;
        this.name = name;
        this.lastname = lastname;
        this.email = email;
        this.password = password;
        this.role = role;
        this.deleted = deleted;
    }

    /**
     * Getter for <code>public.clients.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.clients.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.clients.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.clients.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.clients.lastname</code>.
     */
    public String getLastname() {
        return this.lastname;
    }

    /**
     * Setter for <code>public.clients.lastname</code>.
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * Getter for <code>public.clients.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.clients.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>public.clients.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>public.clients.password</code>.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>public.clients.role</code>.
     */
    public String getRole() {
        return this.role;
    }

    /**
     * Setter for <code>public.clients.role</code>.
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * Getter for <code>public.clients.deleted</code>.
     */
    public Boolean getDeleted() {
        return this.deleted;
    }

    /**
     * Setter for <code>public.clients.deleted</code>.
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Clients (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(lastname);
        sb.append(", ").append(email);
        sb.append(", ").append(password);
        sb.append(", ").append(role);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
