/*
 * This file is generated by jOOQ.
 */
package jooq_generated.tables.pojos;


import java.io.Serializable;


/**
 * The table <code>public.diagnostic_results</code>.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiagnosticResults implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long    id;
    private Long    clientId;
    private Long    diagnosticId;
    private Long    scaleId;
    private Integer result;

    public DiagnosticResults() {}

    public DiagnosticResults(DiagnosticResults value) {
        this.id = value.id;
        this.clientId = value.clientId;
        this.diagnosticId = value.diagnosticId;
        this.scaleId = value.scaleId;
        this.result = value.result;
    }

    public DiagnosticResults(
        Long    id,
        Long    clientId,
        Long    diagnosticId,
        Long    scaleId,
        Integer result
    ) {
        this.id = id;
        this.clientId = clientId;
        this.diagnosticId = diagnosticId;
        this.scaleId = scaleId;
        this.result = result;
    }

    /**
     * Getter for <code>public.diagnostic_results.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.diagnostic_results.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.diagnostic_results.client_id</code>.
     */
    public Long getClientId() {
        return this.clientId;
    }

    /**
     * Setter for <code>public.diagnostic_results.client_id</code>.
     */
    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    /**
     * Getter for <code>public.diagnostic_results.diagnostic_id</code>.
     */
    public Long getDiagnosticId() {
        return this.diagnosticId;
    }

    /**
     * Setter for <code>public.diagnostic_results.diagnostic_id</code>.
     */
    public void setDiagnosticId(Long diagnosticId) {
        this.diagnosticId = diagnosticId;
    }

    /**
     * Getter for <code>public.diagnostic_results.scale_id</code>.
     */
    public Long getScaleId() {
        return this.scaleId;
    }

    /**
     * Setter for <code>public.diagnostic_results.scale_id</code>.
     */
    public void setScaleId(Long scaleId) {
        this.scaleId = scaleId;
    }

    /**
     * Getter for <code>public.diagnostic_results.result</code>.
     */
    public Integer getResult() {
        return this.result;
    }

    /**
     * Setter for <code>public.diagnostic_results.result</code>.
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DiagnosticResults (");

        sb.append(id);
        sb.append(", ").append(clientId);
        sb.append(", ").append(diagnosticId);
        sb.append(", ").append(scaleId);
        sb.append(", ").append(result);

        sb.append(")");
        return sb.toString();
    }
}
