/*
 * This file is generated by jOOQ.
 */
package jooq_generated.tables.pojos;


import java.io.Serializable;


/**
 * The table <code>public.scales</code>.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Scales implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private Long   diagnosticId;
    private String name;
    private String description;

    public Scales() {}

    public Scales(Scales value) {
        this.id = value.id;
        this.diagnosticId = value.diagnosticId;
        this.name = value.name;
        this.description = value.description;
    }

    public Scales(
        Long   id,
        Long   diagnosticId,
        String name,
        String description
    ) {
        this.id = id;
        this.diagnosticId = diagnosticId;
        this.name = name;
        this.description = description;
    }

    /**
     * Getter for <code>public.scales.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.scales.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.scales.diagnostic_id</code>.
     */
    public Long getDiagnosticId() {
        return this.diagnosticId;
    }

    /**
     * Setter for <code>public.scales.diagnostic_id</code>.
     */
    public void setDiagnosticId(Long diagnosticId) {
        this.diagnosticId = diagnosticId;
    }

    /**
     * Getter for <code>public.scales.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.scales.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.scales.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.scales.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Scales (");

        sb.append(id);
        sb.append(", ").append(diagnosticId);
        sb.append(", ").append(name);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
