/*
 * This file is generated by jOOQ.
 */
package jooq_generated;


import jooq_generated.tables.Clients;
import jooq_generated.tables.records.ClientsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClientsRecord> PK_USERS = Internal.createUniqueKey(Clients.CLIENTS, DSL.name("pk_users"), new TableField[] { Clients.CLIENTS.ID }, true);
}
