/*
 * This file is generated by jOOQ.
 */
package jooq_generated;


import jooq_generated.tables.Clients;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.clients</code>.
     */
    public static final Clients CLIENTS = Clients.CLIENTS;
}
