/*
 * This file is generated by jOOQ.
 */
package jooq_generated;


import jooq_generated.tables.Clients;
import jooq_generated.tables.ClientsSummary;
import jooq_generated.tables.Diagnostic;
import jooq_generated.tables.DiagnosticResults;
import jooq_generated.tables.Questions;
import jooq_generated.tables.Recommendations;
import jooq_generated.tables.Scales;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.clients</code>.
     */
    public static final Clients CLIENTS = Clients.CLIENTS;

    /**
     * The table <code>public.clients_summary</code>.
     */
    public static final ClientsSummary CLIENTS_SUMMARY = ClientsSummary.CLIENTS_SUMMARY;

    /**
     * The table <code>public.diagnostic</code>.
     */
    public static final Diagnostic DIAGNOSTIC = Diagnostic.DIAGNOSTIC;

    /**
     * The table <code>public.diagnostic_results</code>.
     */
    public static final DiagnosticResults DIAGNOSTIC_RESULTS = DiagnosticResults.DIAGNOSTIC_RESULTS;

    /**
     * The table <code>public.questions</code>.
     */
    public static final Questions QUESTIONS = Questions.QUESTIONS;

    /**
     * The table <code>public.recommendations</code>.
     */
    public static final Recommendations RECOMMENDATIONS = Recommendations.RECOMMENDATIONS;

    /**
     * The table <code>public.scales</code>.
     */
    public static final Scales SCALES = Scales.SCALES;
}
