/*
 * This file is generated by jOOQ.
 */
package jooq_generated.tables.daos;


import java.util.List;

import jooq_generated.tables.ClientsSummary;
import jooq_generated.tables.records.ClientsSummaryRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * The table <code>public.clients_summary</code>.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientsSummaryDao extends DAOImpl<ClientsSummaryRecord, jooq_generated.tables.pojos.ClientsSummary, Long> {

    /**
     * Create a new ClientsSummaryDao without any configuration
     */
    public ClientsSummaryDao() {
        super(ClientsSummary.CLIENTS_SUMMARY, jooq_generated.tables.pojos.ClientsSummary.class);
    }

    /**
     * Create a new ClientsSummaryDao with an attached configuration
     */
    public ClientsSummaryDao(Configuration configuration) {
        super(ClientsSummary.CLIENTS_SUMMARY, jooq_generated.tables.pojos.ClientsSummary.class, configuration);
    }

    @Override
    public Long getId(jooq_generated.tables.pojos.ClientsSummary object) {
        return object.getClientId();
    }

    /**
     * Fetch records that have <code>client_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<jooq_generated.tables.pojos.ClientsSummary> fetchRangeOfClientId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ClientsSummary.CLIENTS_SUMMARY.CLIENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>client_id IN (values)</code>
     */
    public List<jooq_generated.tables.pojos.ClientsSummary> fetchByClientId(Long... values) {
        return fetch(ClientsSummary.CLIENTS_SUMMARY.CLIENT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>client_id = value</code>
     */
    public jooq_generated.tables.pojos.ClientsSummary fetchOneByClientId(Long value) {
        return fetchOne(ClientsSummary.CLIENTS_SUMMARY.CLIENT_ID, value);
    }

    /**
     * Fetch records that have <code>energy_level BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<jooq_generated.tables.pojos.ClientsSummary> fetchRangeOfEnergyLevel(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ClientsSummary.CLIENTS_SUMMARY.ENERGY_LEVEL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>energy_level IN (values)</code>
     */
    public List<jooq_generated.tables.pojos.ClientsSummary> fetchByEnergyLevel(Integer... values) {
        return fetch(ClientsSummary.CLIENTS_SUMMARY.ENERGY_LEVEL, values);
    }
}
