/*
 * This file is generated by jOOQ.
 */
package jooq_generated.tables.records;


import jooq_generated.tables.ClientsSummary;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * The table <code>public.clients_summary</code>.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientsSummaryRecord extends UpdatableRecordImpl<ClientsSummaryRecord> implements Record2<Long, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.clients_summary.client_id</code>.
     */
    public void setClientId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.clients_summary.client_id</code>.
     */
    public Long getClientId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.clients_summary.energy_level</code>.
     */
    public void setEnergyLevel(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.clients_summary.energy_level</code>.
     */
    public Integer getEnergyLevel() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ClientsSummary.CLIENTS_SUMMARY.CLIENT_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ClientsSummary.CLIENTS_SUMMARY.ENERGY_LEVEL;
    }

    @Override
    public Long component1() {
        return getClientId();
    }

    @Override
    public Integer component2() {
        return getEnergyLevel();
    }

    @Override
    public Long value1() {
        return getClientId();
    }

    @Override
    public Integer value2() {
        return getEnergyLevel();
    }

    @Override
    public ClientsSummaryRecord value1(Long value) {
        setClientId(value);
        return this;
    }

    @Override
    public ClientsSummaryRecord value2(Integer value) {
        setEnergyLevel(value);
        return this;
    }

    @Override
    public ClientsSummaryRecord values(Long value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientsSummaryRecord
     */
    public ClientsSummaryRecord() {
        super(ClientsSummary.CLIENTS_SUMMARY);
    }

    /**
     * Create a detached, initialised ClientsSummaryRecord
     */
    public ClientsSummaryRecord(Long clientId, Integer energyLevel) {
        super(ClientsSummary.CLIENTS_SUMMARY);

        setClientId(clientId);
        setEnergyLevel(energyLevel);
    }
}
