/*
 * This file is generated by jOOQ.
 */
package jooq_generated.tables.records;


import jooq_generated.tables.Clients;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * The table <code>public.clients</code>.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientsRecord extends UpdatableRecordImpl<ClientsRecord> implements Record8<Long, String, String, String, String, String, String, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.clients.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.clients.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.clients.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.clients.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.clients.lastname</code>.
     */
    public void setLastname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.clients.lastname</code>.
     */
    public String getLastname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.clients.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.clients.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.clients.password</code>.
     */
    public void setPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.clients.password</code>.
     */
    public String getPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.clients.role</code>.
     */
    public void setRole(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.clients.role</code>.
     */
    public String getRole() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.clients.gender</code>.
     */
    public void setGender(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.clients.gender</code>.
     */
    public String getGender() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.clients.deleted</code>.
     */
    public void setDeleted(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.clients.deleted</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, String, String, String, String, Boolean> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, String, String, String, String, String, String, Boolean> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Clients.CLIENTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Clients.CLIENTS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Clients.CLIENTS.LASTNAME;
    }

    @Override
    public Field<String> field4() {
        return Clients.CLIENTS.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return Clients.CLIENTS.PASSWORD;
    }

    @Override
    public Field<String> field6() {
        return Clients.CLIENTS.ROLE;
    }

    @Override
    public Field<String> field7() {
        return Clients.CLIENTS.GENDER;
    }

    @Override
    public Field<Boolean> field8() {
        return Clients.CLIENTS.DELETED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getLastname();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getPassword();
    }

    @Override
    public String component6() {
        return getRole();
    }

    @Override
    public String component7() {
        return getGender();
    }

    @Override
    public Boolean component8() {
        return getDeleted();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getLastname();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getPassword();
    }

    @Override
    public String value6() {
        return getRole();
    }

    @Override
    public String value7() {
        return getGender();
    }

    @Override
    public Boolean value8() {
        return getDeleted();
    }

    @Override
    public ClientsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ClientsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ClientsRecord value3(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public ClientsRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public ClientsRecord value5(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public ClientsRecord value6(String value) {
        setRole(value);
        return this;
    }

    @Override
    public ClientsRecord value7(String value) {
        setGender(value);
        return this;
    }

    @Override
    public ClientsRecord value8(Boolean value) {
        setDeleted(value);
        return this;
    }

    @Override
    public ClientsRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, Boolean value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientsRecord
     */
    public ClientsRecord() {
        super(Clients.CLIENTS);
    }

    /**
     * Create a detached, initialised ClientsRecord
     */
    public ClientsRecord(Long id, String name, String lastname, String email, String password, String role, String gender, Boolean deleted) {
        super(Clients.CLIENTS);

        setId(id);
        setName(name);
        setLastname(lastname);
        setEmail(email);
        setPassword(password);
        setRole(role);
        setGender(gender);
        setDeleted(deleted);
    }
}
