/*
 * This file is generated by jOOQ.
 */
package jooq_generated.tables.records;


import jooq_generated.tables.Questions;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * The table <code>public.questions</code>.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuestionsRecord extends UpdatableRecordImpl<QuestionsRecord> implements Record3<Long, Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.questions.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.questions.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.questions.diagnostic_id</code>.
     */
    public void setDiagnosticId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.questions.diagnostic_id</code>.
     */
    public Long getDiagnosticId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.questions.text</code>.
     */
    public void setText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.questions.text</code>.
     */
    public String getText() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Questions.QUESTIONS.ID;
    }

    @Override
    public Field<Long> field2() {
        return Questions.QUESTIONS.DIAGNOSTIC_ID;
    }

    @Override
    public Field<String> field3() {
        return Questions.QUESTIONS.TEXT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getDiagnosticId();
    }

    @Override
    public String component3() {
        return getText();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getDiagnosticId();
    }

    @Override
    public String value3() {
        return getText();
    }

    @Override
    public QuestionsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public QuestionsRecord value2(Long value) {
        setDiagnosticId(value);
        return this;
    }

    @Override
    public QuestionsRecord value3(String value) {
        setText(value);
        return this;
    }

    @Override
    public QuestionsRecord values(Long value1, Long value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuestionsRecord
     */
    public QuestionsRecord() {
        super(Questions.QUESTIONS);
    }

    /**
     * Create a detached, initialised QuestionsRecord
     */
    public QuestionsRecord(Long id, Long diagnosticId, String text) {
        super(Questions.QUESTIONS);

        setId(id);
        setDiagnosticId(diagnosticId);
        setText(text);
    }
}
